MIN_MINUSCULA = 97

MAX_MINUSCULA= 122

MIN_MAIUSCULA = 65

MAX_MAIUSCULA = 90

TAMANHO_ALFABETO = 26

ALFABETO_MAIUSCULO = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

ALFABETO_MINUSCULO = 'abcdefghijklmnopqrstuvwxyz'